# -*- coding: utf-8 -*-
"""TK1_Machine_Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Sqz8if09ySLWljMruH3WqQHkeZ6hbhT

Input semua library yang diperlukan
"""

import matplotlib.pyplot as plt
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import seaborn as sb

"""panggil file"""

data = pd.read_csv('data-luas-panen-dan-produksi-sayur-dki-jakarta-tahun-2013-2017.csv')
print(data)

"""inisiasi variabel yang akan dipakai"""

usageData = data[["tahun", "jenis_tanaman", "luas_panen", "produksi"]]
print(usageData)

for i in usageData:
  if usageData[i].isna().values.any():
    usageData[i] = usageData[i].fillna(usageData[i].mean())

print(usageData)

plt.scatter(usageData["luas_panen"], usageData["produksi"], color="blue")
plt.xlabel("luas_panen (ha)")
plt.ylabel("produksi (kw)")
plt.show()

corr_matrix = usageData.corr()
sb.heatmap(data=corr_matrix, annot=True)
plt.show()

train, test = train_test_split(usageData, test_size = 0.5)
regression = linear_model.LinearRegression()
regression.fit(train[["luas_panen"]], train[["produksi"]])
print('Coefficients: ', regression.coef_)
print('Intercept: ', regression.intercept_)

plt.scatter(train["luas_panen"], train["produksi"], color = 'blue')
plt.plot(train[["luas_panen"]], regression.coef_ * train[["luas_panen"]] + regression.intercept_, '-r')
plt.xlabel("Luas Panen (ha)")
plt.ylabel("Produksi (kw)")
plt.rcParams["figure.figsize"] = [8,8]
plt.show()